default: &default
  adapter: sqlite3
  database: ":memory:"

development:
  <<: *default
  database: leagueside_dev
  username: leagueside

test:
  <<: *default
  database: leagueside_test
  username: leagueside
