default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: leagueside_dev
  username: leagueside
  password: leagueside

test:
  <<: *default
  database: leagueside_test
  username: leagueside
  password: leagueside
